/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateDirectionRequest,
  CreateOperationResponseDTO,
  DeleteDirectionParams,
  Direction,
  UpdateDirectionRequest
} from '../models';




  export const getDirection = (axiosInstance: AxiosInstance = axios.default) => {
const postDirection = (
    createDirectionRequest: CreateDirectionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateOperationResponseDTO>> => {
    return axiosInstance.post(
      `/Direction`,
      createDirectionRequest,options
    );
  }
const getDirection = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Direction[]>> => {
    return axiosInstance.get(
      `/Direction`,options
    );
  }
const deleteDirection = (
    params?: DeleteDirectionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/Direction`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putDirection = (
    updateDirectionRequest: UpdateDirectionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.put(
      `/Direction`,
      updateDirectionRequest,options
    );
  }
return {postDirection,getDirection,deleteDirection,putDirection}};
export type PostDirectionResult = AxiosResponse<CreateOperationResponseDTO>
export type GetDirectionResult = AxiosResponse<Direction[]>
export type DeleteDirectionResult = AxiosResponse<unknown>
export type PutDirectionResult = AxiosResponse<unknown>
