/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PostEduProgramBody
} from '../models';




  export const getEduProgram = (axiosInstance: AxiosInstance = axios.default) => {
const postEduProgram = (
    postEduProgramBody: PostEduProgramBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {const formData = new FormData();
if(postEduProgramBody.file !== undefined) {
 formData.append(`file`, postEduProgramBody.file);
 }

    return axiosInstance.post(
      `/EduProgram`,
      formData,options
    );
  }
const getEduProgram = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/EduProgram`,options
    );
  }
return {postEduProgram,getEduProgram}};
export type PostEduProgramResult = AxiosResponse<void>
export type GetEduProgramResult = AxiosResponse<void>
