name: auditsupport 

services:
 auditsupport:
#   image: kbdrt/auditsupport:1
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  container_name: auditsupport_api
  environment:
      - ConnectionStrings__DefaultConnectionDataBase=Host=db;Port=5432;Database=auditsupport_db;Username=postgres;Password=123
    #   - ConnectionStrings__DefaultConnectionRedis=redis:6379
    #   - ConnectionStrings__DefaultConnectionRabbitMQ=rabbit
  depends_on:
   - db
   - minio
#    - redis
#    - rabbit

 db:
  image: postgres:latest
  ports:
   - "5480:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: auditsupport_db
   POSTGRES_PORT: 5432 
  container_name: auditsupport_postgre
  volumes:
      - postgres_data:/var/lib/postgresql


 minio:
    image: minio/minio
    ports:
      - "9000:9000" 
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    container_name: auditsupport_minio

#  redis:
#   image: redis:latest
#   container_name: todoapi_redis
#   ports:
#    - "6379:6379"
#   volumes:
#       - redis_data:/data  

#  rabbit:
#   image: rabbitmq:management
#   container_name: todoapi_rabbit
#   hostname: rabbit
#   ports:
#     - "5672:5672"
#     - "15672:15672" 
#   environment:
#    RABBITMQ_DEFAULT_USER: guest
#    RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:  
  minio_data:
#   redis_data:  