/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteDirectionParams,
  Direction,
  PostDirectionParams
} from '../models';




  export const getDirection = (axiosInstance: AxiosInstance = axios.default) => {
const postDirection = (
    params?: PostDirectionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/Direction`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getDirection = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/Direction`,options
    );
  }
const deleteDirection = (
    params?: DeleteDirectionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/Direction`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putDirection = (
    direction: Direction, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/Direction`,
      direction,options
    );
  }
return {postDirection,getDirection,deleteDirection,putDirection}};
export type PostDirectionResult = AxiosResponse<void>
export type GetDirectionResult = AxiosResponse<void>
export type DeleteDirectionResult = AxiosResponse<void>
export type PutDirectionResult = AxiosResponse<void>
