/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface AuthSuccessResponse {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  role?: string | null;
}
