/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface UpdateYearRequest {
  yearId?: string;
  startYear?: number;
  /** @nullable */
  description?: string | null;
}
