/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ChangeProgramStatusCommand,
  CreateOperationResponseDTO,
  CreateProgramCommand,
  CreateVersionRequest,
  CreateVersionResponseDTO,
  DeleteProgramCommand,
  EduProgramDTO,
  EduProgramShortDTO,
  GetProgramsWithFilterQuery,
  ShortCheckErrorDTO,
  ShortYearDTO,
  UpdateProgramCommand
} from '../models';
import type { ProgramHistoryDTO } from '../models/programHistoryDTO';




  export const getEduProgram = (axiosInstance: AxiosInstance = axios.default) => {
const postEduProgram = (
    createProgramCommand: CreateProgramCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateOperationResponseDTO>> => {
    return axiosInstance.post(
      `/EduProgram`,
      createProgramCommand,options
    );
  }
const getEduProgram = (
    getProgramsWithFilterQuery: GetProgramsWithFilterQuery, 
    options?: AxiosRequestConfig
): Promise<AxiosResponse<EduProgramShortDTO[]>> => {
    return axiosInstance.get(
      `/EduProgram`, 
      {
        ...options,
        params: getProgramsWithFilterQuery  
      }
    );
}
const deleteEduProgram = (
    deleteProgramCommand: DeleteProgramCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/EduProgram`,{data:
      deleteProgramCommand, ...options}
    );
  }
const patchEduProgram = (
    updateProgramCommand: UpdateProgramCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.patch(
      `/EduProgram`,
      updateProgramCommand,options
    );
  }
const postEduProgramVersion = (
    createVersionRequest: CreateVersionRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateVersionResponseDTO>> => {
    return axiosInstance.post(
      `/EduProgram/Version`,
      createVersionRequest,options
    );
  }
const getEduProgramVersionFileVersionId = (
    versionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/EduProgram/Version/File/${versionId}`,options
    );
  }
const getEduProgramProgramId = (
    programId: string, 
    onlyLastVersion?: boolean, 
    options?: AxiosRequestConfig
): Promise<AxiosResponse<EduProgramDTO>> => {
    return axiosInstance.get(
        `/EduProgram/${programId}`,
        {
            ...options,
            params: {
                ...options?.params,
                onlyLastVersion: onlyLastVersion
            }
        }
    );
}
const getEduProgramVersionVersionId = (
    versionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/EduProgram/Version/${versionId}`,options
    );
  }
const patchEduProgramStatus = (
    changeProgramStatusCommand: ChangeProgramStatusCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.patch(
      `/EduProgram/Status`,
      changeProgramStatusCommand,options
    );
  }
const getEduProgramYearsTeacherId = (
    teacherId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ShortYearDTO[]>> => {
    return axiosInstance.get(
      `/EduProgram/Years/${teacherId}`,options
    );
  }
  const getEduProgramHistory = (
    programId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProgramHistoryDTO[]>> => {
    return axiosInstance.get(
      `/EduProgram/History/${programId}`,options
    );
  }
const getEduProgramErrorsCheckId = (
    checkId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ShortCheckErrorDTO[]>> => {
    return axiosInstance.get(
      `/EduProgram/Errors/${checkId}`,options
    );
  }
return {postEduProgram,getEduProgram,deleteEduProgram,patchEduProgram,postEduProgramVersion,getEduProgramVersionFileVersionId,getEduProgramProgramId,getEduProgramVersionVersionId,patchEduProgramStatus,getEduProgramYearsTeacherId,getEduProgramHistory,getEduProgramErrorsCheckId}};
export type PostEduProgramResult = AxiosResponse<CreateOperationResponseDTO>
export type GetEduProgramResult = AxiosResponse<EduProgramShortDTO[]>
export type DeleteEduProgramResult = AxiosResponse<unknown>
export type PatchEduProgramResult = AxiosResponse<unknown>
export type PostEduProgramVersionResult = AxiosResponse<CreateVersionResponseDTO>
export type GetEduProgramVersionFileVersionIdResult = AxiosResponse<unknown>
export type GetEduProgramProgramIdResult = AxiosResponse<EduProgramDTO>
export type GetEduProgramVersionVersionIdResult = AxiosResponse<unknown>
export type PatchEduProgramStatusResult = AxiosResponse<unknown>
export type GetEduProgramYearsTeacherIdResult = AxiosResponse<ShortYearDTO[]>
export type getEduProgramHistoryResult = AxiosResponse<ProgramHistoryDTO[]>
export type GetEduProgramErrorsCheckIdResult = AxiosResponse<ShortCheckErrorDTO[]>
