/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ChangeProgramStatusCommand,
  CreateProgramCommand,
  DeleteProgramCommand,
  GetEduProgramParams,
  PostEduProgramVersionBody,
  ShortYearDTO,
  UpdateProgramCommand
} from '../models';




  export const getEduProgram = (axiosInstance: AxiosInstance = axios.default) => {
const postEduProgram = (
    createProgramCommand: CreateProgramCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/EduProgram`,
      createProgramCommand,{
    ...options,}
    );
  }
const getEduProgram = (
    params?: GetEduProgramParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/EduProgram`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const deleteEduProgram = (
    deleteProgramCommand: DeleteProgramCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/EduProgram`,{data:
      deleteProgramCommand, ...options}
    );
  }
const patchEduProgram = (
    updateProgramCommand: UpdateProgramCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.patch(
      `/EduProgram`,
      updateProgramCommand,options
    );
  }
const postEduProgramVersion = (
    postEduProgramVersionBody: PostEduProgramVersionBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {const formData = new FormData();
if(postEduProgramVersionBody.ProgramId !== undefined) {
 formData.append(`ProgramId`, postEduProgramVersionBody.ProgramId);
 }
if(postEduProgramVersionBody.Changes !== undefined) {
 formData.append(`Changes`, postEduProgramVersionBody.Changes);
 }
if(postEduProgramVersionBody.File !== undefined) {
 formData.append(`File`, postEduProgramVersionBody.File);
 }

    return axiosInstance.post(
      `/EduProgram/Version`,
      formData,options
    );
  }
const getEduProgramVersionFileVersionId = (
    versionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/EduProgram/Version/File/${versionId}`,options
    );
  }
const getEduProgramProgramId = (
    programId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/EduProgram/${programId}`,options
    );
  }
const getEduProgramVersionVersionId = (
    versionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/EduProgram/Version/${versionId}`,options
    );
  }
const patchEduProgramStatus = (
    changeProgramStatusCommand: ChangeProgramStatusCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.patch(
      `/EduProgram/Status`,
      changeProgramStatusCommand,options
    );
  }
const getEduProgramYearsTeacherId = (
    teacherId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ShortYearDTO[]>> => {
    return axiosInstance.get(
      `/EduProgram/Years/${teacherId}`,options
    );
  }
return {postEduProgram,getEduProgram,deleteEduProgram,patchEduProgram,postEduProgramVersion,getEduProgramVersionFileVersionId,getEduProgramProgramId,getEduProgramVersionVersionId,patchEduProgramStatus,getEduProgramYearsTeacherId}};
export type PostEduProgramResult = AxiosResponse<string>
export type GetEduProgramResult = AxiosResponse<unknown>
export type DeleteEduProgramResult = AxiosResponse<unknown>
export type PatchEduProgramResult = AxiosResponse<unknown>
export type PostEduProgramVersionResult = AxiosResponse<unknown>
export type GetEduProgramVersionFileVersionIdResult = AxiosResponse<unknown>
export type GetEduProgramProgramIdResult = AxiosResponse<unknown>
export type GetEduProgramVersionVersionIdResult = AxiosResponse<unknown>
export type PatchEduProgramStatusResult = AxiosResponse<unknown>
export type GetEduProgramYearsTeacherIdResult = AxiosResponse<ShortYearDTO[]>
