/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateResponse,
  CreateRuleRequest,
  DeleteRuleSectionParams,
  DeleteRuleWordParams,
  GetRuleResponseDTO,
  UpdateRuleRequest
} from '../models';




  export const getRule = (axiosInstance: AxiosInstance = axios.default) => {
const postRuleWord = (
    createRuleRequest: CreateRuleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateResponse>> => {
    return axiosInstance.post(
      `/Rule/Word`,
      createRuleRequest,options
    );
  }
const getRuleWord = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetRuleResponseDTO[]>> => {
    return axiosInstance.get(
      `/Rule/Word`,options
    );
  }
const deleteRuleWord = (
    params?: DeleteRuleWordParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/Rule/Word`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putRuleWord = (
    updateRuleRequest: UpdateRuleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.put(
      `/Rule/Word`,
      updateRuleRequest,options
    );
  }
const postRuleSection = (
    createRuleRequest: CreateRuleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateResponse>> => {
    return axiosInstance.post(
      `/Rule/Section`,
      createRuleRequest,options
    );
  }
const getRuleSection = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetRuleResponseDTO[]>> => {
    return axiosInstance.get(
      `/Rule/Section`,options
    );
  }
const deleteRuleSection = (
    params?: DeleteRuleSectionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/Rule/Section`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putRuleSection = (
    updateRuleRequest: UpdateRuleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.put(
      `/Rule/Section`,
      updateRuleRequest,options
    );
  }
return {postRuleWord,getRuleWord,deleteRuleWord,putRuleWord,postRuleSection,getRuleSection,deleteRuleSection,putRuleSection}};
export type PostRuleWordResult = AxiosResponse<CreateResponse>
export type GetRuleWordResult = AxiosResponse<GetRuleResponseDTO[]>
export type DeleteRuleWordResult = AxiosResponse<unknown>
export type PutRuleWordResult = AxiosResponse<unknown>
export type PostRuleSectionResult = AxiosResponse<CreateResponse>
export type GetRuleSectionResult = AxiosResponse<GetRuleResponseDTO[]>
export type DeleteRuleSectionResult = AxiosResponse<unknown>
export type PutRuleSectionResult = AxiosResponse<unknown>
