/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ChangeYearStatusRequest,
  CreateYearRequest,
  DeleteEduYearParams,
  UpdateYearRequest
} from '../models';




  export const getEduYear = (axiosInstance: AxiosInstance = axios.default) => {
const postEduYear = (
    createYearRequest: CreateYearRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/EduYear`,
      createYearRequest,options
    );
  }
const getEduYear = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/EduYear`,options
    );
  }
const deleteEduYear = (
    params?: DeleteEduYearParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/EduYear`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putEduYear = (
    updateYearRequest: UpdateYearRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.put(
      `/EduYear`,
      updateYearRequest,options
    );
  }
const patchEduYear = (
    changeYearStatusRequest: ChangeYearStatusRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.patch(
      `/EduYear`,
      changeYearStatusRequest,options
    );
  }
return {postEduYear,getEduYear,deleteEduYear,putEduYear,patchEduYear}};
export type PostEduYearResult = AxiosResponse<unknown>
export type GetEduYearResult = AxiosResponse<unknown>
export type DeleteEduYearResult = AxiosResponse<unknown>
export type PutEduYearResult = AxiosResponse<unknown>
export type PatchEduYearResult = AxiosResponse<unknown>
