/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DeleteEduYearParams,
  EduYear,
  PatchEduYearParams,
  PostEduYearParams
} from '../models';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;




  export const getEduYear = (axiosInstance: AxiosInstance = axios.default) => {
const postEduYear = (
    params?: PostEduYearParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/EduYear`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const getEduYear = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/EduYear`,options
    );
  }
const deleteEduYear = (
    params?: DeleteEduYearParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/EduYear`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putEduYear = (
    eduYear: NonReadonly<EduYear>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/EduYear`,
      eduYear,options
    );
  }
const patchEduYear = (
    params?: PatchEduYearParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/EduYear`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {postEduYear,getEduYear,deleteEduYear,putEduYear,patchEduYear}};
export type PostEduYearResult = AxiosResponse<void>
export type GetEduYearResult = AxiosResponse<void>
export type DeleteEduYearResult = AxiosResponse<void>
export type PutEduYearResult = AxiosResponse<void>
export type PatchEduYearResult = AxiosResponse<void>
