/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface ChangeUserEmailRequest {
  userId?: string;
  /** @nullable */
  newEmail?: string | null;
}
