/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface ChangeYearStatusRequest {
  yearId?: string;
  isOpenYear?: boolean;
  isNotificateUsers?: boolean;
}
