/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { ProgramStatuses } from './programStatuses';

export interface ChangeProgramStatusCommand {
  programId?: string;
  newStatus?: ProgramStatuses;
  versionId?: string;
}
