/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface CreateVersionRequest {
  programId?: string;
  /** @nullable */
  changes?: string | null;
  /** @nullable */
  file?: Blob | null;
}
