/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface CreateDirectionRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  shortName?: string | null;
  /** @nullable */
  description?: string | null;
}
