/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface CreateReviewCommand {
  programId?: string;
  auditorId?: string;
  // /** @nullable */
  // commentary?: string | null;
  // isSuccess?: boolean;
  // /** @nullable */
  // file?: Blob | null;
}
