/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface CreateProgramCommand {
  teacherId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  agesOfChildrens?: string | null;
  /** @nullable */
  duration?: string | null;
  yearId?: string;
  /** @nullable */
  directionId?: string | null;
}
