/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { Direction } from './direction';
import type { EduYear } from './eduYear';
import type { ProgramStatuses } from './programStatuses';
import type { ProgramVersion } from './programVersion';
import type { User } from './user';

export interface EduProgram {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  agesOfChildrens?: string | null;
  duration?: number;
  createdDate?: string;
  eduYearId?: string;
  year?: EduYear;
  directionId?: string;
  direction?: Direction;
  teacherId?: string;
  teacher?: User;
  programStatus?: ProgramStatuses;
  /** @nullable */
  versions?: ProgramVersion[] | null;
}
