/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { ProgramStatuses } from './programStatuses';

export interface EduProgramShortDTO {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  agesOfChildrens?: string | null;
  /** @nullable */
  duration?: string | null;
  /** @nullable */
  year?: string | null;
  /** @nullable */
  direction?: string | null;
  /** @nullable */
  teacher?: string | null;
  programStatus?: ProgramStatuses;
}
