/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { ProgramStatuses } from './programStatuses';
import type { ProgramVersionDTO } from './programVersionDTO';

export interface EduProgramDTO {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  agesOfChildrens?: string | null;
  /** @nullable */
  duration?: string | null;
  /** @nullable */
  year?: string | null;
  /** @nullable */
  direction?: string | null;
  directionId?: string;
  /** @nullable */
  teacher?: string | null;
   /** @nullable */
  email?: string | null;
  programStatus?: ProgramStatuses;
  /** @nullable */
  versions?: ProgramVersionDTO[] | null;
}
