/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { ProgramStatuses } from './programStatuses';
import type { ProgramVersion } from './programVersion';

export interface EduProgramDTO {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  agesOfChildrens?: string | null;
  duration?: string;
  /** @nullable */
  year?: string | null;
  /** @nullable */
  direction?: string | null;
  /** @nullable */
  directionId?: string | null;
  /** @nullable */
  teacher?: string | null;
  programStatus?: ProgramStatuses;
  /** @nullable */
  versions?: ProgramVersion[] | null;
}
