/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface EduYear {
  id?: string;
  /** @maxLength 4 */
  startYear?: number;
  /** @maxLength 4 */
  endYear?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  readonly period?: string | null;
  isOpened?: boolean;
}
