/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { ProgramStatuses } from './programStatuses';

export type GetEduProgramParams = {
YearId?: string;
Teachers?: string[];
'Pagination.Page'?: number;
'Pagination.Size'?: number;
Statuses?: ProgramStatuses[];
Directions?: string[];
};
