/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface GetWordRuleResponseDTO {
  ruleId?: string;
  /** @nullable */
  word?: string | null;
  /** @nullable */
  commentary?: string | null;
}
