/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export type HistorySourceType = typeof HistorySourceType[keyof typeof HistorySourceType];


export const HistorySourceType = {
  Program: 0,
  Check: 1,
} as const;

