/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface PersonInitials {
  /** @nullable */
  surname?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  patronymic?: string | null;
  /** @nullable */
  readonly short?: string | null;
}
