/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export type PostEduProgramVersionBody = {
  ProgramId?: string;
  Changes?: string;
  File?: Blob;
};
