/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface ProgramVersionDTO {
  id?: string;
  /** @nullable */
  changes?: string | null;
  fileSize?: number;
  createdDate?: string;
}
