/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export type ProgramStatuses = typeof ProgramStatuses[keyof typeof ProgramStatuses];


export const ProgramStatuses = {
  Created: 0,
  ReadyToCheck: 1,
  Check: 2,
  Checked: 3,
  ReadyToChange: 4,
  Changed: 5,
  ReadyToApprove: 6,
  Deleted: 7,
  Approved: 8,
} as const;

