/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { EduProgram } from './eduProgram';
import type { TechCheck } from './techCheck';

export interface ProgramVersion {
  id?: string;
  version?: number;
  programId?: string;
  program?: EduProgram;
  /** @nullable */
  changes?: string | null;
  fileSize?: number;
  createdDate?: string;
  techCheckId?: string;
  technicalCheck?: TechCheck;
}
