/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export type RuleSectionType = typeof RuleSectionType[keyof typeof RuleSectionType];


export const RuleSectionType = {
  Text: 0,
  Table: 1,
  Lines: 2,
} as const;
