/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export type RuleType = typeof RuleType[keyof typeof RuleType];


export const RuleType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
