/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
export interface ShortReviewResponseDTO {
  id?: string;
  auditor: string;
  createdDate: string;
  isFinished: boolean;
  isSuccess: boolean;
}

