/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { RuleType } from './ruleType';

export interface ShortCheckErrorDTO {
  id?: string;
  ruleSourceId?: string;
  ruleType?: RuleType;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  rule?: string | null;
  wordLength?: number;
  /** @nullable */
  context?: string | null;
  /** @nullable */
  sectionName?: string | null;
  pageNumber?: number;
}
