/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { ShortProgramDTO } from './shortProgramDTO';

export interface ShortYearDTO {
  id?: string;
  /** @nullable */
  period?: string | null;
  isOpened?: boolean;
  /** @nullable */
  programs?: ShortProgramDTO[] | null;
}
