/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { CheckError } from './checkError';
import type { ProgramVersion } from './programVersion';

export interface TechCheck {
  id?: string;
  versionId?: string;
  programVersion?: ProgramVersion;
  createdDate?: string;
  isSuccess?: boolean;
  /** @nullable */
  errors?: CheckError[] | null;
}
