/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface UpdateProgramCommand {
  programId?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  agesOfChildrens?: string | null;
  duration?: string;
  directionId?: string;
}
