/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */

export interface UpdateReviewCommand {
  reviewId?: string;
  /** @nullable */
  commentary?: string | null;
  /** @nullable */
  file?: Blob | null;
  isSuccess?: boolean;
  isFinished?: boolean;
}
