/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import type { PersonInitials } from './personInitials';
import type { Roles } from './roles';

export interface User {
  id?: string;
  initials?: PersonInitials;
  /** @nullable */
  login?: string | null;
  /** @nullable */
  passwordHashed?: string | null;
  /** @nullable */
  email?: string | null;
  role?: Roles;
  isActive?: boolean;
}
