/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateReviewCommand,
  DeleteReviewCommand,
  UpdateReviewCommand
} from '../models';




  export const getReview = (axiosInstance: AxiosInstance = axios.default) => {
const postReview = (
    createReviewCommand: CreateReviewCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/Review`,
      createReviewCommand,options
    );
  }
const deleteReview = (
    deleteReviewCommand: DeleteReviewCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/Review`,{data:
      deleteReviewCommand, ...options}
    );
  }
const patchReview = (
    updateReviewCommand: UpdateReviewCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.patch(
      `/Review`,
      updateReviewCommand,options
    );
  }
const getReviewReviewId = (
    reviewId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/Review/${reviewId}`,options
    );
  }
const getReviewFileReviewId = (
    reviewId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/Review/File/${reviewId}`,options
    );
  }
return {postReview,deleteReview,patchReview,getReviewReviewId,getReviewFileReviewId}};
export type PostReviewResult = AxiosResponse<unknown>
export type DeleteReviewResult = AxiosResponse<unknown>
export type PatchReviewResult = AxiosResponse<unknown>
export type GetReviewReviewIdResult = AxiosResponse<unknown>
export type GetReviewFileReviewIdResult = AxiosResponse<unknown>
