/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateOperationResponseDTO,
  CreateReviewCommand,
  DeleteReviewCommand,
  UpdateReviewCommand
} from '../models';
import type { ShortReviewResponseDTO } from '../models/shortReviewResponseDTO';
import type { GetReviewResponseDTO } from '../models/getReviewResponseDTO';




  export const getReview = (axiosInstance: AxiosInstance = axios.default) => {
const postReview = (
    createReviewCommand: CreateReviewCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateOperationResponseDTO>> => {
    return axiosInstance.post(
      `/Review`,
      createReviewCommand,options
    );
  }
const deleteReview = (
    deleteReviewCommand: DeleteReviewCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/Review`,{data:
      deleteReviewCommand, ...options}
    );
  }
const patchReview = (
    updateReviewCommand: UpdateReviewCommand, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.patch(
      `/Review`,
      updateReviewCommand,options
    );
  }
const getReviewId = (
    reviewId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetReviewResponseDTO>> => {
    return axiosInstance.get(
      `/Review/${reviewId}`,options
    );
  }
  const getReviewsForProgram = (
    programId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ShortReviewResponseDTO[]>> => {
    return axiosInstance.get(
      `/Review/Program/${programId}`,options
    );
  }
const getReviewFileReviewId = (
    reviewId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/Review/File/${reviewId}`,options
    );
  }
return {postReview,deleteReview,patchReview,getReviewId,getReviewsForProgram,getReviewFileReviewId}};
export type PostReviewResult = AxiosResponse<unknown>
export type DeleteReviewResult = AxiosResponse<unknown>
export type PatchReviewResult = AxiosResponse<unknown>
export type GetReviewIdResult = AxiosResponse<GetReviewResponseDTO>
export type GetReviewsForProgram = AxiosResponse<ShortReviewResponseDTO[]>
export type GetReviewFileReviewIdResult = AxiosResponse<unknown>
