/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateUserRequest
} from '../models';




  export const getAdmin = (axiosInstance: AxiosInstance = axios.default) => {
const postAdminRegister = (
    createUserRequest: CreateUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/Admin/register`,
      createUserRequest,options
    );
  }
return {postAdminRegister}};
export type PostAdminRegisterResult = AxiosResponse<unknown>
