/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateResponse,
  CreateSectionRuleRequest,
  CreateWordRuleRequest,
  DeleteRuleSectionParams,
  DeleteRuleWordParams,
  GetSectionRuleResponseDTO,
  GetWordRuleResponseDTO,
  UpdateSectionRuleRequest,
  UpdateWordRuleRequest
} from '../models';




  export const getRule = (axiosInstance: AxiosInstance = axios.default) => {
const postRuleWord = (
    createWordRuleRequest: CreateWordRuleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateResponse>> => {
    return axiosInstance.post(
      `/Rule/Word`,
      createWordRuleRequest,options
    );
  }
const getRuleWord = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetWordRuleResponseDTO[]>> => {
    return axiosInstance.get(
      `/Rule/Word`,options
    );
  }
const deleteRuleWord = (
    params?: DeleteRuleWordParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/Rule/Word`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putRuleWord = (
    updateWordRuleRequest: UpdateWordRuleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.put(
      `/Rule/Word`,
      updateWordRuleRequest,options
    );
  }
const postRuleSection = (
    createSectionRuleRequest: CreateSectionRuleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateResponse>> => {
    return axiosInstance.post(
      `/Rule/Section`,
      createSectionRuleRequest,options
    );
  }
const getRuleSection = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetSectionRuleResponseDTO[]>> => {
    return axiosInstance.get(
      `/Rule/Section`,options
    );
  }
const deleteRuleSection = (
    params?: DeleteRuleSectionParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.delete(
      `/Rule/Section`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const putRuleSection = (
    updateSectionRuleRequest: UpdateSectionRuleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.put(
      `/Rule/Section`,
      updateSectionRuleRequest,options
    );
  }
return {postRuleWord,getRuleWord,deleteRuleWord,putRuleWord,postRuleSection,getRuleSection,deleteRuleSection,putRuleSection}};
export type PostRuleWordResult = AxiosResponse<CreateResponse>
export type GetRuleWordResult = AxiosResponse<GetWordRuleResponseDTO[]>
export type DeleteRuleWordResult = AxiosResponse<unknown>
export type PutRuleWordResult = AxiosResponse<unknown>
export type PostRuleSectionResult = AxiosResponse<CreateResponse>
export type GetRuleSectionResult = AxiosResponse<GetSectionRuleResponseDTO[]>
export type DeleteRuleSectionResult = AxiosResponse<unknown>
export type PutRuleSectionResult = AxiosResponse<unknown>
