/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginUserRequest
} from '../models';




  export const getAuth = (axiosInstance: AxiosInstance = axios.default) => {
const getAuthCheckAuth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/Auth/CheckAuth`,options
    );
  }
const postAuthLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/Auth/Logout`,undefined,options
    );
  }
const postAuthLogin = (
    loginUserRequest: LoginUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/Auth/Login`,
      loginUserRequest,options
    );
  }
return {getAuthCheckAuth,postAuthLogout,postAuthLogin}};
export type GetAuthCheckAuthResult = AxiosResponse<unknown>
export type PostAuthLogoutResult = AxiosResponse<unknown>
export type PostAuthLoginResult = AxiosResponse<unknown>
