/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * AuditSupport
 * OpenAPI spec version: v1
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PostLoginParams
} from '../models';




  export const getAuth = (axiosInstance: AxiosInstance = axios.default) => {
const getCheckauth = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/checkauth`,options
    );
  }
const getLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/logout`,options
    );
  }
const postLogin = (
    params?: PostLoginParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/login`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getCheckauth,getLogout,postLogin}};
export type GetCheckauthResult = AxiosResponse<void>
export type GetLogoutResult = AxiosResponse<void>
export type PostLoginResult = AxiosResponse<void>
